name: KixstarPortals
version: 1.0.0-SNAPSHOT
main: me.kixstar.portals.KixstarPortals
author: cfi2017
api-version: '1.15'
depend: [
  "WorldEdit",
  "FastAsyncWorldEdit"
]
commands: {
  kixstarworlds: {},
  testportalfinder: {},
  testsaveoldblocks: {},
  testloadoldblocks: {},
  testspawnportal: {}
}
permissions: {}